# Generated by Django 4.1.7 on 2023-04-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usersemester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='credit_gpa',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='credit_hours',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='study_level',
        ),
        migrations.AddField(
            model_name='usersemester',
            name='credit_gpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersemester',
            name='credit_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersemester',
            name='gpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersemester',
            name='hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersemester',
            name='study_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
